name: appinio_video_player
description: A custom video player that builds on top of the official video_player package by flutter and adds many functionalities.
version: 1.2.1
homepage: https://github.com/appinioGmbH/flutter_packages
repository: https://github.com/appinioGmbH/flutter_packages

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  video_player: ^2.4.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
